### ISSUE TITLE
automated testing using grinder

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#180]
## TODO first

* [x] Implement `quit` support in gngr and use it grinder (via GngrWebDriver)
* [x] Add an ant task to launch gngr in grinder mode.
* [x] Implement a `check` command in grinder, which will exit with error code when there are regressions.

## Pseudocode for testing
* Checkout grinder and grinderBaseLine repositories.
* Start `xvfb`
* Create a random `key`
* Launch `gngr` in grinder mode with `key`
* Start the webserver in grinder directory
* Run the grinder tests
* Run the `check` command
* :shipit:

**Comment by hrj** [comment]
Automatic tests are now [working fine on Travis-CI](https://travis-ci.org/UprootLabs/UprootLabs/gngr/builds/87137870).
